version: "3.2"
services:
  app:
    command: ["npm", "start"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${APP_PORT:-3000}
        target: 3000
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DB}
